package modelo;
// Generated 10-11-2020 13:52:40 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetallePedido generated by hbm2java
 */
@Entity
@Table(name="detalle_pedido"
    ,catalog="deliveryduoc"
)
public class DetallePedido  implements java.io.Serializable {


     private Integer idDetalle;
     private Pedido pedido;
     private Producto producto;
     private int cantidad;
     private int subtotal;

    public DetallePedido() {
    }

    public DetallePedido(Pedido pedido, Producto producto, int cantidad, int subtotal) {
       this.pedido = pedido;
       this.producto = producto;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_detalle", unique=true, nullable=false)
    public Integer getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(Integer idDetalle) {
        this.idDetalle = idDetalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pedido", nullable=false)
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_producto", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="subtotal", nullable=false)
    public int getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(int subtotal) {
        this.subtotal = subtotal;
    }




}


