package modelo;
// Generated 10-11-2020 13:52:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name="estado"
    ,catalog="deliveryduoc"
)
public class Estado  implements java.io.Serializable {


     private Integer idEstado;
     private String descripcion;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Estado() {
    }

	
    public Estado(String descripcion) {
        this.descripcion = descripcion;
    }
    public Estado(String descripcion, Set<Pedido> pedidos) {
       this.descripcion = descripcion;
       this.pedidos = pedidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_estado", unique=true, nullable=false)
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estado")
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


