package modelo;
// Generated 10-11-2020 13:52:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MetodoPago generated by hbm2java
 */
@Entity
@Table(name="metodo_pago"
    ,catalog="deliveryduoc"
)
public class MetodoPago  implements java.io.Serializable {


     private Integer idMetodo;
     private String descripcion;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public MetodoPago() {
    }

	
    public MetodoPago(String descripcion) {
        this.descripcion = descripcion;
    }
    public MetodoPago(String descripcion, Set<Pedido> pedidos) {
       this.descripcion = descripcion;
       this.pedidos = pedidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_metodo", unique=true, nullable=false)
    public Integer getIdMetodo() {
        return this.idMetodo;
    }
    
    public void setIdMetodo(Integer idMetodo) {
        this.idMetodo = idMetodo;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="metodoPago")
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


