package modelo;
// Generated 10-11-2020 13:52:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="deliveryduoc"
)
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Categoria categoria;
     private PuntoVenta puntoVenta;
     private String nombre;
     private int precio;
     private String imagen;
     private boolean activo;
     private Set<DetallePedido> detallePedidos = new HashSet<DetallePedido>(0);

    public Producto() {
    }

	
    public Producto(Categoria categoria, PuntoVenta puntoVenta, String nombre, int precio, String imagen, boolean activo) {
        this.categoria = categoria;
        this.puntoVenta = puntoVenta;
        this.nombre = nombre;
        this.precio = precio;
        this.imagen = imagen;
        this.activo = activo;
    }
    public Producto(Categoria categoria, PuntoVenta puntoVenta, String nombre, int precio, String imagen, boolean activo, Set<DetallePedido> detallePedidos) {
       this.categoria = categoria;
       this.puntoVenta = puntoVenta;
       this.nombre = nombre;
       this.precio = precio;
       this.imagen = imagen;
       this.activo = activo;
       this.detallePedidos = detallePedidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_producto", unique=true, nullable=false)
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_categoria", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_punto_venta", nullable=false)
    public PuntoVenta getPuntoVenta() {
        return this.puntoVenta;
    }
    
    public void setPuntoVenta(PuntoVenta puntoVenta) {
        this.puntoVenta = puntoVenta;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="precio", nullable=false)
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }

    
    @Column(name="imagen", nullable=false, length=200)
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<DetallePedido> getDetallePedidos() {
        return this.detallePedidos;
    }
    
    public void setDetallePedidos(Set<DetallePedido> detallePedidos) {
        this.detallePedidos = detallePedidos;
    }




}


