package modelo;
// Generated 10-11-2020 13:52:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PuntoVenta generated by hbm2java
 */
@Entity
@Table(name="punto_venta"
    ,catalog="deliveryduoc"
)
public class PuntoVenta  implements java.io.Serializable {


     private Integer idPuntoVenta;
     private Sede sede;
     private String nombre;
     private String empresa;
     private String imagen;
     private Date horaInicio;
     private Date horaFin;
     private boolean activo;
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public PuntoVenta() {
    }

	
    public PuntoVenta(Sede sede, String nombre, String empresa, String imagen, Date horaInicio, Date horaFin, boolean activo) {
        this.sede = sede;
        this.nombre = nombre;
        this.empresa = empresa;
        this.imagen = imagen;
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;
        this.activo = activo;
    }
    public PuntoVenta(Sede sede, String nombre, String empresa, String imagen, Date horaInicio, Date horaFin, boolean activo, Set<Producto> productos, Set<Usuario> usuarios) {
       this.sede = sede;
       this.nombre = nombre;
       this.empresa = empresa;
       this.imagen = imagen;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.activo = activo;
       this.productos = productos;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_punto_venta", unique=true, nullable=false)
    public Integer getIdPuntoVenta() {
        return this.idPuntoVenta;
    }
    
    public void setIdPuntoVenta(Integer idPuntoVenta) {
        this.idPuntoVenta = idPuntoVenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede", nullable=false)
    public Sede getSede() {
        return this.sede;
    }
    
    public void setSede(Sede sede) {
        this.sede = sede;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="empresa", nullable=false, length=100)
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="imagen", nullable=false, length=200)
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="hora_inicio", nullable=false, length=8)
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="hora_fin", nullable=false, length=8)
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }

    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="puntoVenta")
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="puntoVenta")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


