package modelo;
// Generated 10-11-2020 13:52:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEntrega generated by hbm2java
 */
@Entity
@Table(name="tipo_entrega"
    ,catalog="deliveryduoc"
)
public class TipoEntrega  implements java.io.Serializable {


     private Integer idTipoEntrega;
     private String descripcion;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public TipoEntrega() {
    }

	
    public TipoEntrega(String descripcion) {
        this.descripcion = descripcion;
    }
    public TipoEntrega(String descripcion, Set<Pedido> pedidos) {
       this.descripcion = descripcion;
       this.pedidos = pedidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_entrega", unique=true, nullable=false)
    public Integer getIdTipoEntrega() {
        return this.idTipoEntrega;
    }
    
    public void setIdTipoEntrega(Integer idTipoEntrega) {
        this.idTipoEntrega = idTipoEntrega;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoEntrega")
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


