package modelo;
// Generated 10-11-2020 13:52:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ubicacion generated by hbm2java
 */
@Entity
@Table(name="ubicacion"
    ,catalog="deliveryduoc"
)
public class Ubicacion  implements java.io.Serializable {


     private Integer idUbicacion;
     private Sede sede;
     private String nombreEdificio;
     private String piso;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Ubicacion() {
    }

	
    public Ubicacion(Sede sede, String nombreEdificio, String piso) {
        this.sede = sede;
        this.nombreEdificio = nombreEdificio;
        this.piso = piso;
    }
    public Ubicacion(Sede sede, String nombreEdificio, String piso, Set<Pedido> pedidos) {
       this.sede = sede;
       this.nombreEdificio = nombreEdificio;
       this.piso = piso;
       this.pedidos = pedidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_ubicacion", unique=true, nullable=false)
    public Integer getIdUbicacion() {
        return this.idUbicacion;
    }
    
    public void setIdUbicacion(Integer idUbicacion) {
        this.idUbicacion = idUbicacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede", nullable=false)
    public Sede getSede() {
        return this.sede;
    }
    
    public void setSede(Sede sede) {
        this.sede = sede;
    }

    
    @Column(name="nombre_edificio", nullable=false, length=50)
    public String getNombreEdificio() {
        return this.nombreEdificio;
    }
    
    public void setNombreEdificio(String nombreEdificio) {
        this.nombreEdificio = nombreEdificio;
    }

    
    @Column(name="piso", nullable=false, length=50)
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ubicacion")
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


